import type { NextConfig } from 'next'
import { execSync } from 'child_process'
import { readFileSync } from 'fs'
import { resolve } from 'path'
import createNextIntlPlugin from 'next-intl/plugin'

const withNextIntl = createNextIntlPlugin('./src/i18n/request.ts')

// Single source of truth = the annotated git tag (Release Automation v2).
// Resolve the Platform Version + title at build time:
//   1. Prefer the git tag (git describe), matching lowercase v… tags only so
//      historical uppercase V… tags are ignored.
//   2. Fall back to the generated release.json cache when tags aren't visible
//      (e.g. a shallow CI clone). release.json is generated by release.sh and
//      must never be hand-edited.
let platformVersion = 'unknown'
let releaseTitle = ''
try {
  platformVersion = execSync("git describe --tags --abbrev=0 --match 'v[0-9]*'", {
    encoding: 'utf-8',
  }).trim()
  // Title = the annotated tag's subject line.
  releaseTitle = execSync(
    `git for-each-ref --format='%(contents:subject)' refs/tags/${platformVersion}`,
    { encoding: 'utf-8' },
  ).trim()
} catch {
  // git/tags unavailable — fall back to the generated release.json cache.
}
if (platformVersion === 'unknown' || platformVersion === '') {
  try {
    const release = JSON.parse(readFileSync(resolve(process.cwd(), 'release.json'), 'utf-8'))
    platformVersion = release.version ?? 'unknown'
    releaseTitle = release.title ?? ''
  } catch {
    // No cache either — leave as 'unknown'.
  }
}

// All domain-based routing is handled in proxy.ts (middleware).
const nextConfig: NextConfig = {
  // ── Build-time deployment metadata ─────────────────────────────────────────
  // Baked in at build time so client components can read them as NEXT_PUBLIC_*
  // without exposing server-only VERCEL_* variables.
  env: {
    NEXT_PUBLIC_VERCEL_ENV:         process.env.VERCEL_ENV            ?? 'development',
    NEXT_PUBLIC_PLATFORM_VERSION:   platformVersion,
    NEXT_PUBLIC_RELEASE_TITLE:      releaseTitle,
    NEXT_PUBLIC_GIT_COMMIT_SHA:     process.env.VERCEL_GIT_COMMIT_SHA ?? 'local',
    NEXT_PUBLIC_GIT_COMMIT_REF:     process.env.VERCEL_GIT_COMMIT_REF ?? 'local',
    NEXT_PUBLIC_BUILD_TIME:         new Date().toISOString(),
  },
  async headers() {
    return [
      {
        // Prevent Vercel CDN from caching any tenant website response.
        // Without this, a 404 on /[slug] gets cached before middleware runs.
        source: '/(.*)',
        headers: [
          { key: 'Cache-Control', value: 'no-store' },
        ],
      },
      {
        // ── Staging hosts must never be indexed ──────────────────────────────
        // This account has no Vercel Deployment Protection, so dev.abluo.app,
        // preview.abluo.app, every *.preview.abluo.app and every raw
        // *.vercel.app deployment URL are PUBLIC and serve a complete copy of
        // every client website. `X-Robots-Tag: noindex` is the authoritative
        // control — robots.txt only asks a crawler not to FETCH a URL, and a
        // URL linked from anywhere else can still be indexed without ever
        // being fetched.
        //
        // Declarative rather than middleware on purpose: this is matched on the
        // HOST by the routing layer, so it covers EVERY response — pages, API
        // routes (which `proxy.ts`'s matcher excludes), images, static files —
        // and needs no change to proxy.ts's many return points.
        //
        // `has: [{ type: 'host', value }]` wraps `value` in ^…$ and tests it
        // against the lowercased, port-stripped Host header (see `matchHas` in
        // next/dist/shared/lib/router/utils/prepare-destination.js), so the
        // value is a full regex and the wildcard hosts are covered.
        //
        // THE REGEX BELOW MUST STAY BYTE-IDENTICAL TO
        // `STAGING_HOST_REGEX_SOURCE` in src/lib/seo/indexability.ts, which is
        // what robots.txt uses. next.config.ts is loaded by Next's own config
        // loader before the app module graph exists and so cannot import it;
        // src/lib/seo/__tests__/indexability.test.ts reads this file and fails
        // if the two copies drift.
        source: '/(.*)',
        has: [
          {
            type: 'host',
            value: '(?:dev\\.abluo\\.app|(?:.+\\.)?preview\\.abluo\\.app|(?:.+\\.)?vercel\\.app|(?:.+\\.)?localhost)',
          },
        ],
        headers: [
          { key: 'X-Robots-Tag', value: 'noindex, nofollow' },
        ],
      },
    ]
  },
}

export default withNextIntl(nextConfig)
