-- ===========================================================================
-- applied-check.sql — GENERATED by supabase/verify/applied-check.mjs (--sql).
-- Do not hand-edit; edit CATALOG_CHECKS in applied-check.mjs and regenerate.
--
-- WHAT THIS IS: the catalog half of the migration-state check. PostgREST does
-- not expose pg_catalog, so policies, GRANTs, function bodies, triggers and
-- constraints cannot be read from the app. This one statement reads them and
-- returns a verdict per migration.
--
-- HOW TO RUN (Tom):
--   1. Supabase Dashboard -> SQL editor -> New query.
--   2. Paste this whole file. Run it.
--   3. It returns ONE cell of JSON. Copy it into a file, e.g. catalog.json.
--   4. node supabase/verify/applied-check.mjs --merge catalog.json
--
-- IT IS READ-ONLY. One SELECT. No DDL, no DML, no temp objects, no writes.
-- Safe to run against production as often as you like.
-- ===========================================================================

select jsonb_pretty(jsonb_agg(to_jsonb(f) order by f.migration)) as applied_check
from (
  select '003'::text as migration,
         'function public.get_my_owned_tenant_ids() exists'::text as fingerprint,
         (coalesce((select 'prosecdef=' || p.prosecdef::text from pg_proc p where p.proname = 'get_my_owned_tenant_ids' and p.pronamespace = 'public'::regnamespace), 'absent'))::text as observed,
         (case when exists (select 1 from pg_proc p where p.proname = 'get_my_owned_tenant_ids' and p.pronamespace = 'public'::regnamespace) then 'UNDETERMINABLE (present, but schema.sql declares it too)' else 'NOT APPLIED' end)::text as verdict
  union all
  select '004'::text as migration,
         'helpers get_my_tenant_ids + get_my_writable_tenant_ids exist AND handle_new_user still writes profiles'::text as fingerprint,
         ((select count(*)::text || ' of 2 helper functions' from pg_proc p where p.pronamespace = 'public'::regnamespace and p.proname in ('get_my_tenant_ids','get_my_writable_tenant_ids')))::text as observed,
         (case when (select count(*) from pg_proc p where p.pronamespace = 'public'::regnamespace and p.proname in ('get_my_tenant_ids','get_my_writable_tenant_ids')) = 2 then 'UNDETERMINABLE (present, but schema.sql declares them too; see Tier 1 for the profiles column drop, which IS decisive)' else 'NOT APPLIED' end)::text as verdict
  union all
  select '008'::text as migration,
         'col_description on public.leads.project_id (008 writes one)'::text as fingerprint,
         (coalesce(left((select col_description(to_regclass('public.leads'), a.attnum) from pg_attribute a where a.attrelid = to_regclass('public.leads') and a.attname = 'project_id'), 60), 'no comment'))::text as observed,
         (case when (select col_description(to_regclass('public.leads'), a.attnum) from pg_attribute a where a.attrelid = to_regclass('public.leads') and a.attname = 'project_id') is not null then 'APPLIED' when exists (select 1 from pg_attribute a where a.attrelid = to_regclass('public.leads') and a.attname = 'project_id' and not a.attisdropped) then 'APPLIED (NOT VERBATIM) - column present, 008 comment missing' else 'NOT APPLIED' end)::text as verdict
  union all
  select '009'::text as migration,
         'qual of policy "Members can read their projects" contains a RAW project_members subquery (009) rather than get_my_project_ids() (013)'::text as fingerprint,
         (coalesce(left((select qual from pg_policies where schemaname='public' and tablename='projects' and policyname='Members can read their projects'), 200), 'policy absent'))::text as observed,
         (case when (select qual from pg_policies where schemaname='public' and tablename='projects' and policyname='Members can read their projects') ilike '%get_my_project_ids%' then 'UNDETERMINABLE (013 overwrote 009 - the only object 009 touched. 013 existing at all is evidence 009 once ran, but that is an inference, not an observation)' when (select qual from pg_policies where schemaname='public' and tablename='projects' and policyname='Members can read their projects') ilike '%project_members%' then 'APPLIED (009 form still live - 013 NOT applied)' else 'NOT APPLIED (policy is the pre-009 004 form)' end)::text as verdict
  union all
  select '010'::text as migration,
         'body of public.handle_new_user() contains a project_members INSERT (exists in NO other repo file)'::text as fingerprint,
         (coalesce((select 'mentions project_members=' || (p.prosrc ilike '%project_members%')::text || ', tenant_members=' || (p.prosrc ilike '%tenant_members%')::text from pg_proc p where p.proname='handle_new_user' and p.pronamespace='public'::regnamespace), 'function absent'))::text as observed,
         (case when exists (select 1 from pg_proc p where p.proname='handle_user_invited' and p.pronamespace='public'::regnamespace) then 'UNDETERMINABLE (024 has been applied and rewrote handle_new_user, erasing 010 only trace)' when (select p.prosrc from pg_proc p where p.proname='handle_new_user' and p.pronamespace='public'::regnamespace) ilike '%project_members%' then 'APPLIED (despite the file header saying NOT APPLIED)' else 'NOT APPLIED' end)::text as verdict
  union all
  select '011'::text as migration,
         'GRANT SELECT to authenticated on all three of tenant_members, project_members, projects'::text as fingerprint,
         ((select coalesce(string_agg(table_name, ',' order by table_name), 'none') from information_schema.role_table_grants where table_schema='public' and grantee='authenticated' and privilege_type='SELECT' and table_name in ('tenant_members','project_members','projects')))::text as observed,
         (case when (select count(*) from information_schema.role_table_grants where table_schema='public' and grantee='authenticated' and privilege_type='SELECT' and table_name in ('tenant_members','project_members','projects')) = 3 then 'APPLIED' when (select count(*) from information_schema.role_table_grants where table_schema='public' and grantee='authenticated' and privilege_type='SELECT' and table_name in ('tenant_members','project_members','projects')) = 0 then 'NOT APPLIED' else 'PARTIAL - some but not all three grants present' end)::text as verdict
  union all
  select '012'::text as migration,
         'column-level GRANT UPDATE(full_name) on public.profiles to authenticated, with NO table-level UPDATE'::text as fingerprint,
         ((select coalesce(string_agg(column_name || ':' || privilege_type, ',' order by column_name), 'none') from information_schema.column_privileges where table_schema='public' and table_name='profiles' and grantee='authenticated' and privilege_type='UPDATE'))::text as observed,
         (case when exists (select 1 from information_schema.column_privileges where table_schema='public' and table_name='profiles' and grantee='authenticated' and privilege_type='UPDATE' and column_name='full_name') and not exists (select 1 from information_schema.role_table_grants where table_schema='public' and table_name='profiles' and grantee='authenticated' and privilege_type='UPDATE') then 'APPLIED' when exists (select 1 from information_schema.role_table_grants where table_schema='public' and table_name='profiles' and grantee='authenticated' and privilege_type='UPDATE') then 'UNDETERMINABLE - a TABLE-level UPDATE grant exists, which is broader than 012 and masks it' else 'NOT APPLIED' end)::text as verdict
  union all
  select '013'::text as migration,
         'qual of policy "Members can read their projects" calls public.get_my_project_ids()'::text as fingerprint,
         (coalesce(left((select qual from pg_policies where schemaname='public' and tablename='projects' and policyname='Members can read their projects'), 200), 'policy absent'))::text as observed,
         (case when (select qual from pg_policies where schemaname='public' and tablename='projects' and policyname='Members can read their projects') ilike '%get_my_project_ids%' then 'APPLIED' when (select qual from pg_policies where schemaname='public' and tablename='projects' and policyname='Members can read their projects') is null then 'NOT APPLIED (policy absent entirely)' else 'NOT APPLIED (policy present but still the recursive 009 form - live recursion bug)' end)::text as verdict
  union all
  select '014'::text as migration,
         'two named policies on public.inquiries AND GRANT SELECT+UPDATE on inquiries to authenticated'::text as fingerprint,
         ((select 'policies=' || (select count(*) from pg_policies where schemaname='public' and tablename='inquiries' and policyname in ('Members can read inquiries for their tenants and projects','Contributors can update inquiries for their tenants and projects'))::text || ', grants=' || coalesce((select string_agg(privilege_type, '+' order by privilege_type) from information_schema.role_table_grants where table_schema='public' and table_name='inquiries' and grantee='authenticated'), 'none')))::text as observed,
         (case when (select count(*) from pg_policies where schemaname='public' and tablename='inquiries' and policyname in ('Members can read inquiries for their tenants and projects','Contributors can update inquiries for their tenants and projects')) = 2 and (select count(*) from information_schema.role_table_grants where table_schema='public' and table_name='inquiries' and grantee='authenticated' and privilege_type in ('SELECT','UPDATE')) = 2 then 'APPLIED' when (select count(*) from pg_policies where schemaname='public' and tablename='inquiries' and policyname in ('Members can read inquiries for their tenants and projects','Contributors can update inquiries for their tenants and projects')) = 0 and not exists (select 1 from information_schema.role_table_grants where table_schema='public' and table_name='inquiries' and grantee='authenticated') then 'NOT APPLIED' else 'PARTIAL - grants and policies disagree; inspect before acting' end)::text as verdict
  union all
  select '015'::text as migration,
         'table-level GRANT SELECT on public.profiles to authenticated'::text as fingerprint,
         (coalesce((select string_agg(privilege_type, '+' order by privilege_type) from information_schema.role_table_grants where table_schema='public' and table_name='profiles' and grantee='authenticated'), 'none'))::text as observed,
         (case when exists (select 1 from information_schema.role_table_grants where table_schema='public' and table_name='profiles' and grantee='authenticated' and privilege_type='SELECT') then 'APPLIED' else 'NOT APPLIED' end)::text as verdict
  union all
  select '016'::text as migration,
         'GRANT SELECT+UPDATE on form_submissions to authenticated AND both 016 policies'::text as fingerprint,
         ((select 'policies=' || (select count(*) from pg_policies where schemaname='public' and tablename='form_submissions' and policyname in ('Members read their project submissions','Writable roles update their project submissions'))::text || ', authenticated grants=' || coalesce((select string_agg(privilege_type, '+' order by privilege_type) from information_schema.role_table_grants where table_schema='public' and table_name='form_submissions' and grantee='authenticated'), 'none')))::text as observed,
         (case when (select count(*) from pg_policies where schemaname='public' and tablename='form_submissions' and policyname in ('Members read their project submissions','Writable roles update their project submissions')) = 2 and (select count(*) from information_schema.role_table_grants where table_schema='public' and table_name='form_submissions' and grantee='authenticated' and privilege_type in ('SELECT','UPDATE')) = 2 then 'APPLIED' when not exists (select 1 from pg_class c where c.relname='form_submissions' and c.relnamespace='public'::regnamespace) then 'NOT APPLIED' else 'PARTIAL - table exists but grants/policies incomplete' end)::text as verdict
  union all
  select '017'::text as migration,
         'GRANT SELECT on form_events to authenticated AND policy "Members read their project form events"'::text as fingerprint,
         ((select 'policy=' || exists (select 1 from pg_policies where schemaname='public' and tablename='form_events' and policyname='Members read their project form events')::text || ', authenticated grants=' || coalesce((select string_agg(privilege_type, '+' order by privilege_type) from information_schema.role_table_grants where table_schema='public' and table_name='form_events' and grantee='authenticated'), 'none')))::text as observed,
         (case when exists (select 1 from pg_policies where schemaname='public' and tablename='form_events' and policyname='Members read their project form events') and exists (select 1 from information_schema.role_table_grants where table_schema='public' and table_name='form_events' and grantee='authenticated' and privilege_type='SELECT') then 'APPLIED' when not exists (select 1 from pg_class c where c.relname='form_events' and c.relnamespace='public'::regnamespace) then 'NOT APPLIED' else 'PARTIAL - table exists but grant/policy incomplete' end)::text as verdict
  union all
  select '018'::text as migration,
         'service_role holds SELECT+INSERT+UPDATE+DELETE on BOTH form tables (8 rows)'::text as fingerprint,
         ((select count(*)::text || ' of 8 service_role privileges' from information_schema.role_table_grants where table_schema='public' and grantee='service_role' and table_name in ('form_submissions','form_events') and privilege_type in ('SELECT','INSERT','UPDATE','DELETE')))::text as observed,
         (case when (select count(*) from information_schema.role_table_grants where table_schema='public' and grantee='service_role' and table_name in ('form_submissions','form_events') and privilege_type in ('SELECT','INSERT','UPDATE','DELETE')) = 8 then 'APPLIED (weak: Supabase default privileges could in principle produce the same grants - but the live 42501 that 018 was written to fix proves they did not here)' when (select count(*) from information_schema.role_table_grants where table_schema='public' and grantee='service_role' and table_name in ('form_submissions','form_events') and privilege_type in ('SELECT','INSERT','UPDATE','DELETE')) = 0 then 'NOT APPLIED' else 'PARTIAL' end)::text as verdict
  union all
  select '019'::text as migration,
         'constraint form_events_status_check accepts ''skipped'''::text as fingerprint,
         (coalesce((select left(pg_get_constraintdef(c.oid), 160) from pg_constraint c where c.conrelid = to_regclass('public.form_events') and c.conname = 'form_events_status_check'), 'constraint absent (table or constraint missing)'))::text as observed,
         (case when (select pg_get_constraintdef(c.oid) from pg_constraint c where c.conrelid = to_regclass('public.form_events') and c.conname='form_events_status_check') ilike '%skipped%' then 'APPLIED' else 'NOT APPLIED' end)::text as verdict
  union all
  select '020'::text as migration,
         'the three project-grain policy names on public.leads, and the ABSENCE of the three tenant-grain ones'::text as fingerprint,
         ((select coalesce(string_agg(policyname, ' | ' order by policyname), 'no policies') from pg_policies where schemaname='public' and tablename='leads'))::text as observed,
         (case when (select count(*) from pg_policies where schemaname='public' and tablename='leads' and policyname in ('Members read leads for their projects','Writable roles insert leads for their projects','Writable roles update leads for their projects')) = 3 then 'APPLIED' when (select count(*) from pg_policies where schemaname='public' and tablename='leads' and policyname in ('Members can read leads for their tenants','Contributors can insert leads for their tenants','Contributors can update leads for their tenants')) > 0 then 'NOT APPLIED (leads RLS still at TENANT grain)' else 'PARTIAL - neither policy set is intact' end)::text as verdict
  union all
  select '021'::text as migration,
         'GRANT SELECT on public.tenants to authenticated, and nothing wider'::text as fingerprint,
         (coalesce((select string_agg(privilege_type, '+' order by privilege_type) from information_schema.role_table_grants where table_schema='public' and table_name='tenants' and grantee='authenticated'), 'none'))::text as observed,
         (case when (select count(*) from information_schema.role_table_grants where table_schema='public' and table_name='tenants' and grantee='authenticated') = 1 and exists (select 1 from information_schema.role_table_grants where table_schema='public' and table_name='tenants' and grantee='authenticated' and privilege_type='SELECT') then 'APPLIED' when exists (select 1 from information_schema.role_table_grants where table_schema='public' and table_name='tenants' and grantee='authenticated' and privilege_type='SELECT') then 'APPLIED but WIDER than 021 - extra privileges present, investigate' else 'NOT APPLIED' end)::text as verdict
  union all
  select '022'::text as migration,
         'column public.tenants.domain absent, and tenants_domain_key / tenants_domain_idx gone with it'::text as fingerprint,
         ((select 'domain column=' || exists (select 1 from pg_attribute a where a.attrelid=to_regclass('public.tenants') and a.attname='domain' and not a.attisdropped)::text || ', domain indexes=' || (select count(*) from pg_indexes where schemaname='public' and tablename='tenants' and indexname like '%domain%')::text))::text as observed,
         (case when not exists (select 1 from pg_attribute a where a.attrelid=to_regclass('public.tenants') and a.attname='domain' and not a.attisdropped) then 'APPLIED' else 'NOT APPLIED' end)::text as verdict
  union all
  select '023'::text as migration,
         'UNIQUE (tenant_id, slug) on public.projects exists AND no UNIQUE (slug) survives'::text as fingerprint,
         ((select coalesce(string_agg(c.conname || '=' || pg_get_constraintdef(c.oid), ' | ' order by c.conname), 'none') from pg_constraint c where c.conrelid=to_regclass('public.projects') and c.contype='u'))::text as observed,
         (case when exists (select 1 from pg_constraint c where c.conrelid=to_regclass('public.projects') and c.contype='u' and pg_get_constraintdef(c.oid) = 'UNIQUE (tenant_id, slug)') and not exists (select 1 from pg_constraint c where c.conrelid=to_regclass('public.projects') and c.contype='u' and pg_get_constraintdef(c.oid) = 'UNIQUE (slug)') then 'APPLIED' when exists (select 1 from pg_constraint c where c.conrelid=to_regclass('public.projects') and c.contype='u' and pg_get_constraintdef(c.oid) = 'UNIQUE (slug)') then 'NOT APPLIED (global UNIQUE (slug) still in force)' else 'PARTIAL - neither expected constraint shape found' end)::text as verdict
  union all
  select '024'::text as migration,
         'function public.handle_user_invited() + trigger on_auth_user_invited on auth.users, and handle_new_user() no longer touches membership tables'::text as fingerprint,
         ((select 'handle_user_invited=' || exists (select 1 from pg_proc p where p.proname='handle_user_invited' and p.pronamespace='public'::regnamespace)::text || ', triggers=' || coalesce((select string_agg(t.tgname, ',' order by t.tgname) from pg_trigger t where t.tgrelid=to_regclass('auth.users') and not t.tgisinternal), 'none') || ', handle_new_user touches membership=' || coalesce((select (p.prosrc ilike '%tenant_members%' or p.prosrc ilike '%project_members%')::text from pg_proc p where p.proname='handle_new_user' and p.pronamespace='public'::regnamespace), 'n/a')))::text as observed,
         (case when exists (select 1 from pg_proc p where p.proname='handle_user_invited' and p.pronamespace='public'::regnamespace) and exists (select 1 from pg_trigger t where t.tgrelid=to_regclass('auth.users') and not t.tgisinternal and t.tgname='on_auth_user_invited') and not coalesce((select (p.prosrc ilike '%tenant_members%' or p.prosrc ilike '%project_members%') from pg_proc p where p.proname='handle_new_user' and p.pronamespace='public'::regnamespace), true) then 'APPLIED' when exists (select 1 from pg_proc p where p.proname='handle_user_invited' and p.pronamespace='public'::regnamespace) then 'PARTIAL - handle_user_invited exists but trigger or handle_new_user rewrite is missing. DO NOT re-enable self-signup' else 'NOT APPLIED - the privilege-escalation trigger shape is still live' end)::text as verdict
) f;
