/**
 * Blog category page — /[locale]/[tenant]/category/[slug]
 *
 * WHY THIS ROUTE EXISTS
 * The old Webflow site published one page per blog category at /category/<slug>.
 * Five of those URLs survived the content consolidation and are indexed; five
 * more were merged into survivors. Without this route every one of them 404s
 * the moment DNS moves, taking their inbound links and ranking with them.
 *
 * WHERE THE CATEGORIES COME FROM
 * Not from a document type. Categories are per-website CONFIGURATION — they
 * live in the blog module's config (`project.moduleInstallations[].config
 * .categories`), which is where their labels and colours already were and what
 * `resolveCategoriesFor` already reads to draw the badges on post cards. A
 * `blogCategory` document type also exists in the blog module schema, unused
 * and holding zero documents; adding pages on top of it would have created a
 * second, divergent source of truth for the same names.
 *
 * The description, the retired-key list and the noindex flag come from the same
 * entries, generated by the `supportsRouting` flag on the manifest field — see
 * modules/types.ts. Nothing on this page is hardcoded, and Claudia can rename a
 * category, retitle its page or retire it entirely from the Modules pane.
 *
 * Satisfies the Publicly Routable Content Pattern (CLAUDE.md):
 *   • primary lookup on the category key
 *   • 301 via redirectFrom when the primary lookup misses
 *   • notFound() only after both have missed
 *   • hreflang alternates across supportedLocales
 */

import type { Metadata } from 'next'
import { notFound, redirect } from 'next/navigation'
import { tenantClient, fetchDesignSystemById } from '@/lib/sanity/client'
import {
  localeConfigQuery,
  designSystemQuery,
  websiteSiteConfigQuery,
  projectModuleConfigQuery,
  postsByCategoryQuery,
} from '@/lib/sanity/queries'
import { resolveDesignSystemInheritance } from '@/lib/sanity/design-system-resolver'
import { getEnabledModuleIds, type ProjectModuleConfig } from '@/lib/modules/config'
import {
  findRoutableCategory,
  charsPerMinute,
  DEFAULT_CHARS_PER_MINUTE,
} from '@/lib/modules/categories'
import type {
  LocaleConfig,
  SupportedLocale,
  DesignSystem,
  WebsiteSiteConfig,
  Post,
} from '@/lib/sanity/types'
import { BlogListingSection } from '@/components/sections/BlogListingSection'
import { isProduction, isDev } from '@/lib/deployment'
import { asUrlProjectSegment } from '@/lib/tenancy/ids'

export const dynamic = 'force-dynamic'

const MODULE_ID = 'blog'
const PAGE_SIZE = 24

interface PageProps {
  params: Promise<{ tenant: string; locale: string; slug: string }>
}

/**
 * One fetch path shared by generateMetadata and the page body so the two can
 * never disagree about whether a category exists — the failure mode where a
 * page 404s while still emitting a <title> for the thing it could not find.
 */
async function load(tenantId: ReturnType<typeof asUrlProjectSegment>, locale: string, slug: string) {
  const { fetchForTenant } = tenantClient(tenantId)

  const localeConfig = await fetchForTenant<LocaleConfig>(localeConfigQuery, {})
  const defaultLocale: SupportedLocale = localeConfig?.defaultLocale ?? 'en'
  const supportedLocales = localeConfig?.supportedLocales ?? [defaultLocale]

  const moduleConfig = await fetchForTenant<ProjectModuleConfig>(projectModuleConfigQuery, {
    locale,
    defaultLocale,
  })

  const enabledModuleIds = getEnabledModuleIds(moduleConfig)
  // Null means unresolved and fails open, per the gating contract; an empty
  // array means resolved-and-none, which really does gate the route off.
  const blogEnabled = enabledModuleIds === null || enabledModuleIds.includes(MODULE_ID)

  const { category, redirectTo } = findRoutableCategory(
    slug,
    moduleConfig,
    MODULE_ID,
    locale,
    defaultLocale
  )

  return { fetchForTenant, defaultLocale, supportedLocales, moduleConfig, enabledModuleIds, blogEnabled, category, redirectTo }
}

// ─── Metadata ─────────────────────────────────────────────────────────────────

export async function generateMetadata({ params }: PageProps): Promise<Metadata> {
  const { tenant: rawTenantId, locale, slug } = await params
  const tenantId = asUrlProjectSegment(rawTenantId)

  const { fetchForTenant, defaultLocale, supportedLocales, category } = await load(tenantId, locale, slug)
  if (!category) return {}

  const config = await fetchForTenant<WebsiteSiteConfig>(websiteSiteConfigQuery, { locale, defaultLocale })

  const title = category.title
    ? `${category.title}${config?.siteName ? ` — ${config.siteName}` : ''}`
    : (config?.siteName ?? '')

  // The category URL is the same segment in every locale, so alternates are a
  // straight product of supportedLocales — no slug map needed.
  const languages: Record<string, string> = {}
  for (const l of supportedLocales) languages[l] = `/${l}/${tenantId}/category/${category.key}`

  const noindex = category.noindex === true || !isProduction() || isDev()

  return {
    title,
    description: category.description,
    alternates: { canonical: `/${locale}/${tenantId}/category/${category.key}`, languages },
    robots: noindex ? { index: false, follow: false } : undefined,
    openGraph: { title, description: category.description, type: 'website' },
  }
}

// ─── Page ─────────────────────────────────────────────────────────────────────

export default async function BlogCategoryPage({ params }: PageProps) {
  const { tenant: rawTenantId, locale, slug } = await params
  const tenantId = asUrlProjectSegment(rawTenantId)

  const { fetchForTenant, defaultLocale, moduleConfig, blogEnabled, category, redirectTo } =
    await load(tenantId, locale, slug)

  if (!blogEnabled) notFound()

  // A retired category. 301 rather than 404: these were merged during the
  // migration and their old URLs are still linked from the live site.
  if (redirectTo) redirect(`/${locale}/${tenantId}/category/${redirectTo}`)
  if (!category) notFound()

  const [designSystem, posts] = await Promise.all([
    (async () => {
      const raw = await fetchForTenant<DesignSystem>(designSystemQuery, {})
      return resolveDesignSystemInheritance(raw, fetchDesignSystemById)
    })(),
    fetchForTenant<Post[]>(postsByCategoryQuery, {
      locale,
      defaultLocale,
      categoryKey: category.key,
      offset: 0,
      limit: PAGE_SIZE,
      charsPerMinute: charsPerMinute(moduleConfig, MODULE_ID) || DEFAULT_CHARS_PER_MINUTE,
    }),
  ])

  // The category page IS the blog index filtered — same cards, same grid, same
  // empty state. Building a second listing design here would drift from the
  // blog index the first time either was touched.
  const section = {
    _key: `category-${category.key}`,
    _type: 'blogListingSection' as const,
    background: 'usePagePattern',
    title: category.title,
    subtitle: category.description,
    layout: 'grid' as const,
    posts: posts ?? [],
    viewAllLabel: undefined,
    viewAllHref: undefined,
  }

  return (
    <BlogListingSection
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      section={section as any}
      surface="surface1"
      designSystem={designSystem}
      locale={locale}
      tenantId={tenantId}
      fromParam="blog"
    />
  )
}
